kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-aggregator
  namespace: logging
  labels:
    k8s-app: fluentd-aggregator
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>

  output.conf: |-
    <source>
      @type forward
      port 24224
    </source>
    
    <match **>
      @type copy
      deep_copy true
      <store>
        @type stdout
      </store>
      <store>
        @id elasticsearch
        @type elasticsearch
        logstash_format true
        include_timestamp true
        logstash_prefix cluster-logs
        # Important (required to connect with elasticsearch with https request)
        scheme https
        ssl_version TLSv1_2
        include_tag_key true
        hosts https://e2elogs.test.openebs.io:443/es/
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer.aggregator
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 3
          flush_interval 2s
          retry_forever
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 8
          overflow_action block
        </buffer>
      </store>
    </match>
